# Welcome to Jekyll!
#

# Site settings
title: Shreyas Angara
description: |
  A first-year student at the University of Virginia  
owner: Shreyas Angara # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: shreyas00023@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "shreyasangara.me" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/shreyas00023
  linkedin-square: https://linkedin.com/in/shreyas-angara-088781163/
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
permalink: pretty
#sass:
#  style: compressed
